# DaemonSet ensures that a pod runs on each node in the cluster

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: myapp-daemonset
  # manages the pods with the label app: myapp
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: us.icr.io/<your SN labs namespace>/myapp:v1
        ports:
        - containerPort: 3000
          name: http
      # tolerations allow pods to be scheduled onto node with matching taints.
      # here, it tolerates that taint with the key node-role.kubernetes.io/master and the effect NoSchedule, meaning it can be scheduled on nodes with the master role
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
